"""init

Revision ID: 03865cdfe0c9
Revises: 
Create Date: 2021-01-30 19:41:44.357370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03865cdfe0c9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('miniappconfig',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('appid', sa.String(), nullable=True, comment='微信小程序appid'),
    sa.Column('app_secret', sa.String(), nullable=True, comment='微信小程序app_secret'),
    sa.Column('author', sa.String(), nullable=True, comment='小程序作者'),
    sa.Column('remarks', sa.String(), nullable=True, comment='备注'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_miniappconfig_id'), 'miniappconfig', ['id'], unique=False)
    op.create_table('miniappuser',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('app_id', sa.Integer(), nullable=True, comment='系统中小程序的id'),
    sa.Column('openid', sa.String(), nullable=True, comment='微信用户在此小程序中的openid'),
    sa.Column('session_key', sa.String(), nullable=True, comment='用户的session_key'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='注册时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_miniappuser_app_id'), 'miniappuser', ['app_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_miniappuser_app_id'), table_name='miniappuser')
    op.drop_table('miniappuser')
    op.drop_index(op.f('ix_miniappconfig_id'), table_name='miniappconfig')
    op.drop_table('miniappconfig')
    # ### end Alembic commands ###
