"""add invite user

Revision ID: 396fd784fc2f
Revises: 03865cdfe0c9
Create Date: 2021-01-31 12:22:03.031495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '396fd784fc2f'
down_revision = '03865cdfe0c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inviteuser',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('app_id', sa.Integer(), nullable=True, comment='系统中小程序的id'),
    sa.Column('openid', sa.String(), nullable=True, comment='用户的openid'),
    sa.Column('invite_openid', sa.String(), nullable=True, comment='被邀请的用户的openid'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='邀请时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inviteuser_app_id'), 'inviteuser', ['app_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inviteuser_app_id'), table_name='inviteuser')
    op.drop_table('inviteuser')
    # ### end Alembic commands ###
