"""add tips api

Revision ID: 40f0d5f47088
Revises: ec763a57c436
Create Date: 2021-01-31 14:57:48.279561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40f0d5f47088'
down_revision = 'ec763a57c436'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
