"""add ad table

Revision ID: 4f2e086ef4e4
Revises: 40f0d5f47088
Create Date: 2021-01-31 17:16:58.103220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f2e086ef4e4'
down_revision = '40f0d5f47088'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adhistory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('app_id', sa.Integer(), nullable=True, comment='系统中小程序的id'),
    sa.Column('openid', sa.String(), nullable=True, comment='用户的openid'),
    sa.Column('status', sa.Boolean(), nullable=True, comment='本次观看广告是否有效'),
    sa.Column('cover_id', sa.Integer(), nullable=True, comment='红包封面id'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_adhistory_app_id'), 'adhistory', ['app_id'], unique=False)
    op.add_column('miniapptip', sa.Column('created_at', sa.DateTime(), nullable=True, comment='邀请时间'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('miniapptip', 'created_at')
    op.drop_index(op.f('ix_adhistory_app_id'), table_name='adhistory')
    op.drop_table('adhistory')
    # ### end Alembic commands ###
