"""fix invite table

Revision ID: 5c2abd9a4da3
Revises: 4f2e086ef4e4
Create Date: 2021-02-01 00:06:27.046131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c2abd9a4da3'
down_revision = '4f2e086ef4e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inviteuser', sa.Column('cover_id', sa.Integer(), nullable=True, comment='封面id'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inviteuser', 'cover_id')
    # ### end Alembic commands ###
