"""fix openapi

Revision ID: a34c65c94a46
Revises: e6ee170779fe
Create Date: 2021-02-02 23:14:51.880583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a34c65c94a46'
down_revision = 'e6ee170779fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('redcoverreceived', sa.Column('openid', sa.String(), nullable=True, comment='用户的openid'))
    op.drop_column('redcoverreceived', 'openapi')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('redcoverreceived', sa.Column('openapi', sa.VARCHAR(), autoincrement=False, nullable=True, comment='用户的openid'))
    op.drop_column('redcoverreceived', 'openid')
    # ### end Alembic commands ###
