"""add received

Revision ID: e6ee170779fe
Revises: 5c2abd9a4da3
Create Date: 2021-02-01 20:25:52.881475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6ee170779fe'
down_revision = '5c2abd9a4da3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('redcoverreceived',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('app_id', sa.Integer(), nullable=True, comment='系统中小程序的id'),
    sa.Column('openapi', sa.String(), nullable=True, comment='用户的openid'),
    sa.Column('cover_id', sa.Integer(), nullable=True, comment='红包封面的id'),
    sa.Column('red_cover_serial', sa.String(), nullable=True, comment='使用的序列号'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_redcoverreceived_app_id'), 'redcoverreceived', ['app_id'], unique=False)
    op.create_table('redcoverserial',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('app_id', sa.Integer(), nullable=True, comment='系统中小程序的id'),
    sa.Column('cover_id', sa.Integer(), nullable=True, comment='红包封面的id'),
    sa.Column('red_cover_serial', sa.String(), nullable=True, comment='封面序列号'),
    sa.Column('status', sa.Boolean(), nullable=True, comment='序列号状态，False表示被人领取了'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_redcoverserial_app_id'), 'redcoverserial', ['app_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_redcoverserial_app_id'), table_name='redcoverserial')
    op.drop_table('redcoverserial')
    op.drop_index(op.f('ix_redcoverreceived_app_id'), table_name='redcoverreceived')
    op.drop_table('redcoverreceived')
    # ### end Alembic commands ###
