name: 部署服务

on:
  push:
    branches:
      - main
        #paths-ignore:
        #- README.md

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps: # 自动化步骤
      - uses: actions/checkout@v2 # 第一步，下载代码仓库

      - name: Deploy to Server # 第二步，rsync推文件
        uses: AEnterprise/rsync-deploy@v1.0 # 使用别人包装好的步骤镜像
        env:
          DEPLOY_KEY: ${{ secrets.ALI_STUDENTS }} # 引用配置，SSH私钥
          ARGS: -avz --delete --exclude='*.pyc' # rsync参数，排除.pyc文件
          SERVER_PORT: "22" # SSH端口
          FOLDER: ./ # 要推送的文件夹，路径相对于代码仓库的根目录
          SERVER_IP: ${{ secrets.SSH_HOST }} # 引用配置，服务器的host名（IP或者域名domain.com）
          USERNAME: ${{ secrets.SSH_USER }} # 引用配置，服务器登录名
          SERVER_DESTINATION: /root/project/site/ # 部署到目标文件夹
            # - name: Restart server # 第三步，重启服务
            #   uses: appleboy/ssh-action@master
            #   with:
            #     host: ${{ secrets.SSH_HOST }} # 下面三个配置与上一步类似
            #     username: ${{ secrets.SSH_USER }}
            #     key: ${{ secrets.ALI_STUDENTS }}
            #     # 重启的脚本，根据自身情况做相应改动，一般要做的是migrate数据库以及重启服务器
            #     script: |
            #       cd /root/project/site/
            #       python manage.py migrate
            #       supervisorctl restart web
